# Generated by Django 4.2.8 on 2023-12-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mp3_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TRACK_ID', models.CharField(max_length=255)),
                ('MP3_URL', models.URLField()),
                ('DURATION', models.IntegerField()),
                ('TAGS', models.CharField(max_length=255)),
                ('BPM', models.IntegerField()),
                ('TEMPO', models.CharField(max_length=255)),
                ('WEATHER', models.CharField(max_length=255)),
                ('TIME', models.CharField(max_length=255)),
            ],
        ),
    ]
